# Generated by Django 3.0.2 on 2020-01-24 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('breed', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='dog_pics')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('payer', models.TextField(blank=True)),
                ('purpose', models.ManyToManyField(to='base.Dog')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='guardian',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Guardian'),
        ),
    ]
