# Generated by Django 3.0.2 on 2020-01-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200124_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Guardian'),
        ),
    ]
