# Generated by Django 3.0.2 on 2020-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_dog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='fixed',
            field=models.BooleanField(default=True),
        ),
    ]
